//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEconomicPlatform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancialPlannerIS322DEntities : DbContext
    {
        public FinancialPlannerIS322DEntities()
            : base("name=FinancialPlannerIS322DEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesIncome> CategoriesIncome { get; set; }
        public virtual DbSet<CategoriesOutcome> CategoriesOutcome { get; set; }
        public virtual DbSet<IncomeBudgetSettings> IncomeBudgetSettings { get; set; }
        public virtual DbSet<Incomes> Incomes { get; set; }
        public virtual DbSet<OutcomeBudgetSettings> OutcomeBudgetSettings { get; set; }
        public virtual DbSet<Outcomes> Outcomes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
