//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEconomicPlatform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancialPlannerEntities : DbContext
    {
        public FinancialPlannerEntities()
            : base("name=FinancialPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesIncome> CategoriesIncomes { get; set; }
        public virtual DbSet<CategoriesOutcome> CategoriesOutcomes { get; set; }
        public virtual DbSet<IncomeBudgetSetting> IncomeBudgetSettings { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<OutcomeBudgetSetting> OutcomeBudgetSettings { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
